"""
Agent D: Notifications & Alerts
================================
Agent D consumes alerts generated by Agent B (delay/cost variance detection)
and broadcasts them through two channels:

  1. **Firestore** — saved to the ``notifications`` collection so the React
     frontend can fetch and display them in the UI.
  2. **Telegram**  — pushed to the Project Manager's Telegram chat for
     instant mobile access.

Alert categories supported:
  - doc_submission        Document submission deadlines
  - payment_due           Payment deadlines
  - account_receivable    Outstanding receivables
  - extension_of_time     EOT notices / approvals
  - delay_detected        Schedule delay flags
  - cost_overrun          Cost variance flags
  - permit_renewal        Permit / license renewals
  - general               Catch-all

Author: Khaidhir (Agent D)
"""

from typing import Dict, List, Any, Optional
import logging
from datetime import datetime, timedelta
import uuid

from backend.agents.agent_d.telegram_notifier import TelegramNotifier

logger = logging.getLogger(__name__)


# ── Demo / test alerts ────────────────────────────────────────────
# Used when Agent B hasn't provided real alerts yet
DEMO_ALERTS: List[Dict[str, Any]] = [
    {
        "category": "doc_submission",
        "severity": "high",
        "title": "Submit Q2 Progress Report",
        "message": "The quarterly progress report for Phase 2 must be submitted to JKR before the deadline to avoid liquidated damages.",
        "days_remaining": 3,
    },
    {
        "category": "payment_due",
        "severity": "critical",
        "title": "Progress Payment #4 Due",
        "message": "Payment of RM 45,000 to sub-contractor Bina Jaya Sdn Bhd is due. Failure to pay may trigger work stoppage.",
        "days_remaining": 5,
    },
    {
        "category": "account_receivable",
        "severity": "medium",
        "title": "Outstanding Claim from Client",
        "message": "Variation Order VO-012 amounting to RM 120,000 has not been acknowledged by the client. Follow up required.",
        "days_remaining": 14,
    },
    {
        "category": "extension_of_time",
        "severity": "high",
        "title": "EOT Application Deadline",
        "message": "Extension of Time application for rain delay (12 days) must be submitted to S.O. within the contractual window.",
        "days_remaining": 7,
    },
    {
        "category": "permit_renewal",
        "severity": "medium",
        "title": "CIDB Permit Renewal Required",
        "message": "The CIDB G7 license for the main contractor expires soon. Renewal must be initiated to maintain compliance.",
        "days_remaining": 21,
    },
    {
        "category": "delay_detected",
        "severity": "critical",
        "title": "Schedule Delay Detected",
        "message": "Milestone 'Structural Completion Block A' is overdue by 5 days. Current variance exceeds the 3-day threshold.",
        "days_remaining": 0,
    },
]


class AgentD:
    """
    Notifications & Alerts agent.

    Reads alerts from the pipeline state (populated by Agent B), persists
    them to Firestore for UI consumption, and dispatches them via Telegram.
    """

    def __init__(
        self,
        firestore_client: Optional[Any] = None,
        telegram_notifier: Optional[TelegramNotifier] = None,
        use_demo_alerts: bool = True,
    ):
        """
        Args:
            firestore_client:  Firestore client for saving notifications.
            telegram_notifier: Telegram notifier instance.
            use_demo_alerts:   If True, inject demo alerts when the incoming
                               alert list is empty (for hackathon demo).
        """
        self.db = firestore_client
        self.telegram = telegram_notifier or TelegramNotifier()
        self.use_demo_alerts = use_demo_alerts

    # ── Main entry point ─────────────────────────────────────

    async def process_alerts(
        self,
        project_id: str,
        alerts: List[Dict[str, Any]],
        project_name: str = "",
    ) -> Dict[str, Any]:
        """
        Process a list of alerts: save to Firestore, send to Telegram.

        Args:
            project_id:   Firestore project ID.
            alerts:       List of alert dicts from Agent B.
            project_name: Human-readable project name for messages.

        Returns:
            Dict with processing summary.
        """
        logger.info(f"[Agent D] Processing alerts for project {project_id}")

        # Fall back to demo alerts for hackathon demo
        if not alerts and self.use_demo_alerts:
            logger.info("[Agent D] No alerts from Agent B — using demo alerts")
            alerts = DEMO_ALERTS

        # Enrich each alert with metadata
        enriched = self._enrich_alerts(alerts, project_id, project_name)

        result = {
            "project_id": project_id,
            "processed_at": datetime.utcnow().isoformat(),
            "total_alerts": len(enriched),
            "saved_to_firestore": 0,
            "telegram_sent": False,
            "notifications": enriched,
            "errors": [],
        }

        # ── Step 1: Save each alert to Firestore ────────────
        for alert in enriched:
            try:
                if self.db:
                    await self.db.create_alert(project_id, alert)
                    result["saved_to_firestore"] += 1
                else:
                    # No Firestore client — still count as "saved" for demo
                    result["saved_to_firestore"] += 1
            except Exception as exc:
                err = f"Firestore save error: {exc}"
                logger.error(f"[Agent D] {err}")
                result["errors"].append(err)

        logger.info(
            f"[Agent D] Saved {result['saved_to_firestore']}/{len(enriched)} "
            f"alerts to Firestore"
        )

        # ── Step 2: Send batch summary to Telegram ──────────
        try:
            tg_result = await self.telegram.send_alerts_batch(
                alerts=enriched,
                project_name=project_name,
            )
            result["telegram_sent"] = tg_result.get("success", False)
            if not tg_result.get("success"):
                result["errors"].append(
                    f"Telegram: {tg_result.get('error', 'unknown')}"
                )
        except Exception as exc:
            err = f"Telegram send error: {exc}"
            logger.error(f"[Agent D] {err}")
            result["errors"].append(err)

        logger.info(
            f"[Agent D] Done — {result['total_alerts']} alerts processed, "
            f"Telegram={'✓' if result['telegram_sent'] else '✗'}"
        )
        return result

    # ── Helpers ───────────────────────────────────────────────

    def _enrich_alerts(
        self,
        alerts: List[Dict[str, Any]],
        project_id: str,
        project_name: str,
    ) -> List[Dict[str, Any]]:
        """
        Add standard metadata fields to each alert dict.
        """
        enriched = []
        now = datetime.utcnow()

        for alert in alerts:
            enriched_alert = {
                **alert,
                "id": alert.get("id", str(uuid.uuid4())),
                "project_id": project_id,
                "project_name": project_name or alert.get("project_name", ""),
                "status": alert.get("status", "active"),
                "created_at": alert.get("created_at", now.isoformat()),
                "category": alert.get("category", "general"),
                "severity": alert.get("severity", "medium"),
            }

            # Compute a due_date if days_remaining is provided
            days = alert.get("days_remaining")
            if days is not None and "due_date" not in alert:
                enriched_alert["due_date"] = (
                    now + timedelta(days=int(days))
                ).strftime("%Y-%m-%d")

            enriched.append(enriched_alert)

        return enriched
